version: "3.5"  # optional since v1.27.0
services:
  elasticsearch-local:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
    container_name: elasticsearch-local
    environment:
      - discovery.type=single-node
    volumes:
      - ~/docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana-local:
    image: "docker.elastic.co/kibana/kibana:7.12.0"
    container_name: kibana-local
    environment:
      SERVER_NAME: "kibana.example.org"
      ELASTICSEARCH_HOSTS: "http://elasticsearch-local:9200"
    ports:
      - 5601:5601